// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HmcsfoBHZD2h9bi690ceuim3ddlZu7k',
    appId: '1:498759047624:web:dec1f59a1db10751f088fd',
    messagingSenderId: '498759047624',
    projectId: 'mentorshipapp-2c45f',
    authDomain: 'mentorshipapp-2c45f.firebaseapp.com',
    storageBucket: 'mentorshipapp-2c45f.firebasestorage.app',
    measurementId: 'G-HWKY9YFWK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2YXI4RQoGj_K7m01B5nZjjiUtG4-IPbI',
    appId: '1:498759047624:android:a3540ce4fe1ec928f088fd',
    messagingSenderId: '498759047624',
    projectId: 'mentorshipapp-2c45f',
    storageBucket: 'mentorshipapp-2c45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqz0IHilgv73SO_cPb35FDIOeZ9PhujQ',
    appId: '1:498759047624:ios:34aa1dcf1e0c56ecf088fd',
    messagingSenderId: '498759047624',
    projectId: 'mentorshipapp-2c45f',
    storageBucket: 'mentorshipapp-2c45f.firebasestorage.app',
    iosBundleId: 'com.example.mentorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqz0IHilgv73SO_cPb35FDIOeZ9PhujQ',
    appId: '1:498759047624:ios:34aa1dcf1e0c56ecf088fd',
    messagingSenderId: '498759047624',
    projectId: 'mentorshipapp-2c45f',
    storageBucket: 'mentorshipapp-2c45f.firebasestorage.app',
    iosBundleId: 'com.example.mentorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5HmcsfoBHZD2h9bi690ceuim3ddlZu7k',
    appId: '1:498759047624:web:a9d3b733fea1670af088fd',
    messagingSenderId: '498759047624',
    projectId: 'mentorshipapp-2c45f',
    authDomain: 'mentorshipapp-2c45f.firebaseapp.com',
    storageBucket: 'mentorshipapp-2c45f.firebasestorage.app',
    measurementId: 'G-T5QW3VCGLC',
  );
}
